spring:
  application:
    name: quiz-espro
  datasource:
    url: jdbc:postgresql://db.teayeipgyrtypvyubwiv.supabase.co:5432/postgres
    username: postgres
    password: i*F?Zb%jgT2%H+M
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



